apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
  # TODO: set namespace (match Deployment)
  labels:
    app.kubernetes.io/name: mern-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mern-frontend
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mern-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
