apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
data:
  PORT: "3001"
  CORS_ORIGIN: "TODO_SET_CORS_ORIGIN"
