apiVersion: v1
kind: Service
metadata:
  name: backend
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
`