apiVersion: v1
kind: Service
metadata:
  name: mongo
  # TODO: set namespace
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: mern-stack
    app.kubernetes.io/managed-by: k8s-manifests
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: database
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
